import { TimelineDetail } from "../../components/Page/PageContext";

export const CREATOR_DETAILS: TimelineDetail[] = [
  {
    company: "w3ichen.github.io",
    position: "Portfolio Website v1",
    startDate: { year: 2019, month: 11 },
    endDate: { year: 2021, month: 7 },
    location: "Edmonton, Canada",
    skills: [
      "Art",
      "Photography",
      "Videography",
      "CS",
      "AI",
      "TensorFlow",
      "WebDev",
      "HTML",
      "CSS",
      "JavaScript",
      "Linux",
      "Python",
      "Arduino",
      "Unity",
      "CAD",
      "SolidWorks",
      "Animation",
      "Maya",
      "Blender",
    ],
    url: "https://w3ichen.github.io",
  },
  {
    company: "UAlberta Taekwondo Club",
    position: "Social Media Coordinator",
    startDate: { year: 2020, month: 2 },
    endDate: { year: 2022, month: 4 },
    logo: "creator/uatkd_logo.jpg",
    location: "Edmonton, Canada",
    skills: ["Athletics", "Social Media", "Photography", "Videography"],
    url: "/uatkd",
  },
];
