import { TimelineDetail } from "../../components/Page/PageContext";

export const ENTREPRENEUR_DETAILS: TimelineDetail[] = [
  {
    company: "Chief Technology Officer (CTO)",
    position: "BackSCNR",
    startDate: { year: 2021, month: 8 },
    endDate: "Present",
    logo: "entrepreneur/backscnr_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "Healthcare",
      "Startup",
      "AI",
      "3D",
      "Cloud Computing",
      "Python",
      "WebDev",
      "Django",
      "ReactJS",
      "ThreeJS",
    ],
    url: "/backscnr",
  },
  {
    company: "Co-founder, Chief Technology Officer (CTO)",
    position: "MecSimCalc",
    startDate: { year: 2021, month: 6 },
    endDate: "Present",
    logo: "entrepreneur/mecsimcalc_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "Engineering",
      "Startup",
      "Cloud Computing",
      "AWS",
      "Python",
      "WebDev",
      "Django",
      "ReactJS",
      "Leadership",
    ],
    url: "/mecsimcalc",
  },
  {
    company: "UAlberta Taekwondo Club",
    position: "President",
    startDate: { year: 2022, month: 5 },
    endDate: { year: 2023, month: 4 },
    logo: "creator/uatkd_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "Athletics",
      "Leadership",
      "Conflict Resolution",
      "Public Speaking",
      "Networking",
    ],
    url: "/uatkd",
  },
];
