import { TimelineDetail } from "../../components/Page/PageContext";

export const SWE_DETAILS: TimelineDetail[] = [
  {
    company: "Chief Technology Officer (CTO)",
    position: "BackSCNR",
    startDate: { year: 2021, month: 8 },
    endDate: "Present",
    logo: "entrepreneur/backscnr_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "Healthcare",
      "Startup",
      "AI",
      "3D",
      "Cloud Computing",
      "Python",
      "WebDev",
      "Django",
      "ReactJS",
      "ThreeJS",
    ],
    url: "/backscnr",
  },
  {
    company: "Co-founder, Chief Technology Officer (CTO)",
    position: "MecSimCalc",
    startDate: { year: 2021, month: 6 },
    endDate: "Present",
    logo: "entrepreneur/mecsimcalc_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "Engineering",
      "Startup",
      "Cloud Computing",
      "AWS",
      "Python",
      "WebDev",
      "Django",
      "ReactJS",
      "Leadership",
    ],
    url: "/mecsimcalc",
  },
  {
    company: "Huawei Canada",
    position: "AI Researcher Intern",
    startDate: { year: 2022, month: 5 },
    endDate: { year: 2022, month: 12 },
    logo: "swe/huawei_logo.jpg",
    location: "Edmonton, Canada",
    skills: [
      "AI",
      "Research",
      "CS",
      "Python",
      "PyTorch",
      "Linux",
      "NVIDIA CUDA",
      "Anaconda",
      "Draw.io",
    ],
    url: "/huawei",
  },
  {
    company: "Drivewyze",
    position: "Software Developer Intern",
    startDate: { year: 2021, month: 1 },
    endDate: { year: 2021, month: 8 },
    logo: "swe/drivewyze_logo.jpg",
    location: "Edmonton, Canada",
    skills: ["WebDev", "NextJS", "ReactJS", "ReduxJS", "Jira"],
    url: "/drivewyze",
  },
  {
    company: "University of Alberta Engineering",
    position: "Research Assistant",
    startDate: { year: 2020, month: 6 },
    endDate: { year: 2023, month: 12 },
    logo: "swe/ualberta_eng_logo.jpg",
    location: "Edmonton, Canada",
    skills: ["Engineering", "Research", "CivE", "BME", "Python"],
    url: "/ualberta-eng",
  },
  {
    company: "weichen.fyi Github",
    position: "Portfolio Website v2",
    startDate: { year: 2024, month: 12 },
    endDate: { year: 2025, month: 1 },
    location: "Edmonton, Canada",
    skills: ["WebDev", "NextJS", "ReactJS", "TypeScript", "Git"],
    url: "https://github.com/w3ichen/weichen.fyi",
  },
];
